# @package _global_

llm:
  _target_: gigaevo.llm.models.MultiModelRouter
  _convert_: all
  models:
    - _target_: gigaevo.llm.strict_chat_openai.strict_chat_openai
    
      model: ${model_name}
      api_key: ${oc.env:OPENAI_API_KEY,null}
      temperature: ${temperature}
      max_tokens: ${max_tokens}
      base_url: ${llm_base_url}
  probabilities: [1.0]
  writer: ${writer}
